# environment.yml for SPTnet
name: myenv
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.9.12
  - scipy
  - h5py
  - tqdm
  - matplotlib
  - pandas
  - ipython
  - pip
  - pip:
      - opencv-python-headless
      - positional-encodings[pytorch]
